logging:
  level:
    root: info
    '[org.springframework.web]': debug
#    '[org.springframework.cloud]': debug
    '[org.springframework.jdbc.core]': trace

management:
  endpoints:
    web:
      exposure:
        include: refresh

spring:
  application:
    name: catalog-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: false  # In production, set to true
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/polardb_catalog
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5

server:
  port: 9001
  tomcat:
    # TCP 연결을 수락하고 실제로 HTTP 요청을 받기까지 톰캣이 최대한 기다리는 시간.
    # DoS(Denial-of-Service) 공격을 방지하는 데 도움.
    connection-timeout: 2s
    # 새로운 HTTP 요청을 기다리는 동안 연결을 유지하는 시간.
    keep-alive-timeout: 15s
    threads:
      # 최대 요청 처리 스레드 수(default = 200).
      max: 50
      # 쓰레드 풀(thread pool)에 항상 유지해야 하는 최소의 쓰레드 수(default = 10).
      min-spare: 5

polar:
  greeting: Welcome to the local book catalog!
